### ISSUE TITLE
Getting stuck trying to log in to Google Photos

### ISSUE THREAD

**Issue by codepo8** [vikas5914/google-photos-backup#2]
Seems Chromium isn't considered a safe browser:
<img width="416" alt="image" src="https://github.com/vikas5914/google-photos-backup/assets/13508/d12e330c-bdbd-478f-91c5-6b0f693a479a">

**Comment by vikas5914** [comment]
@codepo8 Are you using Linux?

**Comment by codepo8** [comment]
No, MacOS

**Comment by vikas5914** [comment]
@codepo8 I will try on MacOs and let you know.

**Comment by vikas5914** [comment]
@codepo8 I just tried on MacOS with Chromium, and it worked. 

Are you on the latest code, and Do you have 2FA enabled?

**Comment by vikas5914** [comment]
@codepo8 Please check now; I have added the option to use chrome or edge instead of Chorium.
