### ISSUE TITLE
TimeOutError when downloading Photos

### ISSUE THREAD

**Issue by markcs** [vikas5914/google-photos-backup#4]
Hi,
I'm getting a few different errors when trying to download the photos.  Eventually it will start working again, but I'm not sure why the script fails or if it can be made more robust?

This TimeOutError stops me form downloading any further photos.  When I use the headless=false flag, I see the browser load up, the photo load up and then a page that say 'This site can't be reached' The webpage at https://lh3.googleusercontent.com/...........
 
Ideas appreciated and extra robustness would be great!

-------------------------------------
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.waitForEvent: Timeout 30000ms exceeded while waiting for event "download"
=========================== logs ===========================
waiting for event "download"
============================================================
    at downloadPhoto (file:///root/git/google-photos-backup/index.js:91:32)
    at file:///root/git/google-photos-backup/index.js:60:9 {
  name: 'TimeoutError'
}

Node.js v18.13.0

**Comment by vikas5914** [comment]
@markcs, your internet cannot connect to the google photos server (lh3.googleus). Sometimes this happens. I suggest you install a VPN like https://1.1.1.1/ and try,

**Comment by markcs** [comment]
No it isn't that.

I think it was actually a disk full issue. I see why there appears to be a timeout. 

Maybe something you could check in the script and error differently?

**Comment by vikas5914** [comment]
@markcs, the error is coming from the browser, and there is no way to know why the error occurred. In your case, it was disk full; in some cases, it was an internet issue.
